# Site settings
title: Mikhaila Friske
email: frisk028@umn.edu
description: > # this means to ignore newlines until "baseurl:"
  Copyright (c) Mikhaila Friske
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: friskenation
github_username:  frisk028

# Build settings
markdown: kramdown
